//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MailerTestData {
    
    private MailerTestDataCompany[] companiesField;
    
    private MailerTestDataPayeDocument[] payeDocumentsField;
    
    private MailerTestDataPayrollDocument[] payrollDocumentsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Company", IsNullable=false)]
    public MailerTestDataCompany[] Companies {
        get {
            return this.companiesField;
        }
        set {
            this.companiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("PayeDocument", IsNullable=false)]
    public MailerTestDataPayeDocument[] PayeDocuments {
        get {
            return this.payeDocumentsField;
        }
        set {
            this.payeDocumentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("PayrollDocument", IsNullable=false)]
    public MailerTestDataPayrollDocument[] PayrollDocuments {
        get {
            return this.payrollDocumentsField;
        }
        set {
            this.payrollDocumentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MailerTestDataCompany {
    
    private string nameField;
    
    private string emailField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MailerTestDataPayeDocument {
    
    private string fileNameField;
    
    private string sendToField;
    
    private string sentToField;
    
    private string expectedSubjectField;
    
    private string actualSubjectField;
    
    /// <remarks/>
    public string FileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    public string SendTo {
        get {
            return this.sendToField;
        }
        set {
            this.sendToField = value;
        }
    }
    
    /// <remarks/>
    public string SentTo {
        get {
            return this.sentToField;
        }
        set {
            this.sentToField = value;
        }
    }
    
    /// <remarks/>
    public string ExpectedSubject {
        get {
            return this.expectedSubjectField;
        }
        set {
            this.expectedSubjectField = value;
        }
    }
    
    /// <remarks/>
    public string ActualSubject {
        get {
            return this.actualSubjectField;
        }
        set {
            this.actualSubjectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MailerTestDataPayrollDocument {
    
    private string fileNameField;
    
    private string sendToField;
    
    private string sentToField;
    
    private string expectedSubjectField;
    
    private string actualSubjectField;
    
    /// <remarks/>
    public string FileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    public string SendTo {
        get {
            return this.sendToField;
        }
        set {
            this.sendToField = value;
        }
    }
    
    /// <remarks/>
    public string SentTo {
        get {
            return this.sentToField;
        }
        set {
            this.sentToField = value;
        }
    }
    
    /// <remarks/>
    public string ExpectedSubject {
        get {
            return this.expectedSubjectField;
        }
        set {
            this.expectedSubjectField = value;
        }
    }
    
    /// <remarks/>
    public string ActualSubject {
        get {
            return this.actualSubjectField;
        }
        set {
            this.actualSubjectField = value;
        }
    }
}
